policy_path: "/home/yy/Coding/Genesis/examples/logs/go2-walking/exported_policy_300.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/go2/scene.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10

kps: [20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0] 
kds: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5] 

default_angles: [0.1,  0.8,  -1.5,  -0.1, 0.8, -1.5, 
                 0.1,  1.0,  -1.5,  -0.1, 1.0, -1.5] 
# Mujoco joint order:
mujoco_joint_names: [
  "FL_hip_joint",
  "FL_thigh_joint",
  "FL_calf_joint",
  "FR_hip_joint",
  "FR_thigh_joint",
  "FR_calf_joint",
  "RL_hip_joint",
  "RL_thigh_joint",
  "RL_calf_joint",
  "RR_hip_joint",
  "RR_thigh_joint",
  "RR_calf_joint"
]

# Genesis joint order:
model_joint_names: [
  "FL_hip_joint",
  "FL_thigh_joint",
  "FL_calf_joint",
  "FR_hip_joint",
  "FR_thigh_joint",
  "FR_calf_joint",
  "RL_hip_joint",
  "RL_thigh_joint",
  "RL_calf_joint",
  "RR_hip_joint",
  "RR_thigh_joint",
  "RR_calf_joint"
  # "FR_hip_joint",
  # "FR_thigh_joint",
  # "FR_calf_joint",
  # "FL_hip_joint",
  # "FL_thigh_joint",
  # "FL_calf_joint",
  # "RR_hip_joint",
  # "RR_thigh_joint",
  # "RR_calf_joint",
  # "RL_hip_joint",
  # "RL_thigh_joint",
  # "RL_calf_joint"
]

lin_vel_scale: 2.0
ang_vel_scale: 0.25 
dof_pos_scale: 1.0 
dof_vel_scale: 0.05 
action_scale: 0.25 
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 12
num_obs: 45

cmd_init: [0.4, 0, 0]